import numpy as np, pandas as pd, scipy.stats as st, matplotlib
matplotlib.use("Agg"); import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
df = pd.read_csv("hiring_practice.csv")
print(df.shape); print(df.head(3))
s = df.test_score.dropna(); e = df.years_experience
print(df[["years_experience","test_score","hired"]].describe().round(3))
print("score mean/median/mode", s.mean(), s.median(), s.mode().tolist(), "skew", st.skew(s))
print("exp mean/median/mode", e.mean(), e.median(), e.mode().tolist(), "skew", st.skew(e))
print("degree mode", df.degree.mode()[0])
dev = s - s.mean()
print("RMS of dev (SD, ddof0)", np.sqrt((dev**2).mean()), "std ddof1", s.std(), "n", len(s))
print("RMS of score itself", np.sqrt((s**2).mean()))
q1,q2,q3 = s.quantile([.25,.5,.75]); iqr=q3-q1; lo,hi=q1-1.5*iqr,q3+1.5*iqr
print("Q", q1,q2,q3,"IQR",iqr,"fences",lo,hi,"outliers",sorted(s[(s<lo)|(s>hi)].tolist()))
qe = e.quantile([.25,.75]); ie=qe.iloc[1]-qe.iloc[0]; print("exp Q",qe.tolist(),"fence hi",qe.iloc[1]+1.5*ie, "out", sorted(e[e>qe.iloc[1]+1.5*ie].tolist()))
m, sd = s.mean(), s.std()
z = (s-m)/sd
for k in [1,2,3]: print(f"within {k}sd actual", (z.abs()<=k).mean(), "normal", st.norm.cdf(k)-st.norm.cdf(-k))
print("P(score>=80) actual", (s>=80).mean(), "normal approx", 1-st.norm.cdf((80-m)/sd), "z80", (80-m)/sd)
print("P(50<=s<=70) actual", ((s>=50)&(s<=70)).mean(), "normal", st.norm.cdf((70-m)/sd)-st.norm.cdf((50-m)/sd))
for p in [.1,.25,.5,.75,.9,.95]: print("pct",p,"actual",s.quantile(p),"normal",m+st.norm.ppf(p)*sd)
print("z of 85", (85-m)/sd, "percentile", st.norm.cdf((85-m)/sd), "actual", (s<=85).mean())
print("score in 10s: mean", m/10, "sd", sd/10)
# groupby estimation
g = df.groupby("gender").hired.agg(["mean","count","sum"])
g["se"]=np.sqrt(g["mean"]*(1-g["mean"])/g["count"]); g["lo"]=g["mean"]-1.96*g.se; g["hi"]=g["mean"]+1.96*g.se
print(g)
d=g.loc["M","mean"]-g.loc["F","mean"]; se_d=np.sqrt(g.loc["M","se"]**2+g.loc["F","se"]**2); print("diff",d,"se unpooled",se_d,"CI",d-1.96*se_d,d+1.96*se_d)
pp = df.hired.mean(); se0=np.sqrt(pp*(1-pp)*(1/287+1/313)); print("pooled p",pp,"se0",se0,"z",d/se0, "p", 2*st.norm.sf(d/se0))
ct = pd.crosstab(df.gender, df.hired); chi=st.chi2_contingency(ct,correction=False); print(ct, "\nexpected", chi[3], "chi2", chi[0], chi[1], chi[2])
a=df[df.gender=="M"].test_score.dropna(); b=df[df.gender=="F"].test_score.dropna()
print("t welch", st.ttest_ind(a,b,equal_var=False), a.mean(), b.mean(), a.std(), b.std(), len(a), len(b))
print("diff score", a.mean()-b.mean(), "se", np.sqrt(a.var()/len(a)+b.var()/len(b)))
# correlation
d2 = df.dropna()
print(d2[["years_experience","test_score","hired"]].corr().round(3))
x=d2.test_score; y=d2.hired; n=len(d2)
zx=(x-x.mean())/x.std(ddof=0); zy=(y-y.mean())/y.std(ddof=0); r=(zx*zy).mean(); print("r by z-products", r, "n", n)
t=r*np.sqrt(n-2)/np.sqrt(1-r**2); print("r test t", t, 2*st.t.sf(abs(t),n-2))
print("r score in 10s", np.corrcoef(x/10,y)[0,1], "r reversed", np.corrcoef(y,x)[0,1])
r_e=np.corrcoef(d2.years_experience,d2.test_score)[0,1]; print("r exp-score", r_e, "p", st.pearsonr(d2.years_experience,d2.test_score))
# regression hired~score
sdx, sdy = x.std(ddof=0), y.std(ddof=0); b1 = r*sdy/sdx; b0=y.mean()-b1*x.mean()
print("means", x.mean(), y.mean(), "SDs", sdx, sdy, "slope", b1, "intercept", b0)
fit=smf.ols("hired ~ test_score", d2).fit(); print(fit.params, fit.bse, fit.tvalues, fit.pvalues, fit.conf_int())
res = y-(b0+b1*x); print("RMSE actual", np.sqrt((res**2).mean()), "formula", np.sqrt(1-r**2)*sdy, "sigma_hat (n-2)", np.sqrt((res**2).sum()/(n-2)))
print("pred at 80", b0+b1*80, "at 50", b0+b1*50, "at 30", b0+b1*30, "at 100", b0+b1*100)
# reverse regression: score on hired
b_xy = r*sdx/sdy; print("slope score~hired", b_xy, "score mean hired", x[y==1].mean(), "not", x[y==0].mean())
print("z hired=1", (1-y.mean())/sdy, "pred score z", r*(1-y.mean())/sdy, "pred score", x.mean()+r*(1-y.mean())/sdy*sdx)
print("score 2SD above:", x.mean()+2*sdx, "pred hired", y.mean()+r*2*sdy, "z", r*2)
print("product slopes", b1*b_xy, r**2)
# graph of averages
bins = pd.cut(x, [0,40,50,55,60,65,70,75,80,90,101])
ga = d2.groupby(bins, observed=True).hired.agg(["mean","count"]); ga["mid"]=d2.groupby(bins,observed=True).test_score.mean(); print(ga)
# exp regression for a nicer continuous example: score ~ years? r ~0. Use years->hired as well
# FIGURES
plt.rcParams.update({"font.size":10})
fig,ax=plt.subplots(1,2,figsize=(10,3.6))
ax[0].hist(s,bins=25,density=True,color="#9ecae1",edgecolor="white")
xx=np.linspace(20,105,300); ax[0].plot(xx,st.norm.pdf(xx,m,sd),"r-",lw=1.8,label="Normal(mean, SD)")
ax[0].axvline(m,color="k",ls="-",lw=1,label=f"mean {m:.1f}"); ax[0].axvline(s.median(),color="k",ls="--",lw=1,label=f"median {s.median():.0f}")
ax[0].set(title="test_score histogram",xlabel="test_score"); ax[0].legend(fontsize=8)
ax[1].boxplot([s],vert=False,widths=.5); ax[1].set(title="test_score boxplot (1.5 IQR fences)",xlabel="test_score",yticks=[])
for v,l in [(q1,"Q1"),(q2,"Q2"),(q3,"Q3"),(lo,"fence"),(hi,"fence")]: ax[1].axvline(v,color="gray",ls=":",lw=.8); ax[1].text(v,1.33,l,ha="center",fontsize=8)
plt.tight_layout(); plt.savefig("stats-book/fig/dist.png",dpi=150)
fig,ax=plt.subplots(figsize=(4.2,3.8)); st.probplot(s,dist="norm",plot=ax); ax.set(title="Normal Q-Q plot of test_score"); plt.tight_layout(); plt.savefig("stats-book/fig/qq.png",dpi=150)
rng=np.random.default_rng(0)
fig,ax=plt.subplots(1,2,figsize=(10,3.6))
ax[0].scatter(x,y+rng.uniform(-.05,.05,n),s=5,alpha=.3,label="applicants (jittered)")
ax[0].plot(ga["mid"],ga["mean"],"o-",color="darkorange",label="graph of averages")
xx=np.linspace(25,100,10); ax[0].plot(xx,b0+b1*xx,"r-",label="regression line")
ax[0].axhline(0,c="gray",ls=":"); ax[0].axhline(1,c="gray",ls=":"); ax[0].set(xlabel="test_score",ylabel="hired",title="hired vs test_score"); ax[0].legend(fontsize=8)
ax[1].scatter(b0+b1*x,res,s=5,alpha=.35); ax[1].axhline(0,color="k",lw=1); ax[1].set(xlabel="fitted value",ylabel="residual",title="residual plot (LPM)")
plt.tight_layout(); plt.savefig("stats-book/fig/reg.png",dpi=150)
# regression effect diagram with standardized simulated data r=0.5 (illustration)
Z=rng.multivariate_normal([0,0],[[1,.5],[.5,1]],800)
fig,ax=plt.subplots(figsize=(4.6,4.2)); ax.scatter(Z[:,0],Z[:,1],s=4,alpha=.3,color="gray")
t_=np.linspace(-3,3,10); ax.plot(t_,t_,"k--",label="SD line (slope 1)"); ax.plot(t_,.5*t_,"r-",label="regression of y on x (slope r)"); ax.plot(.5*t_,t_,"b-",label="regression of x on y")
ax.set(xlim=(-3,3),ylim=(-3,3),xlabel="x (z-score)",ylabel="y (z-score)",title="regression effect, r = 0.5"); ax.legend(fontsize=7,loc="upper left"); ax.set_aspect("equal"); plt.tight_layout(); plt.savefig("stats-book/fig/regeffect.png",dpi=150)
